### PR TITLE
Splitting Model and Trainer + compatibility with plugin system

### PR DESCRIPTION
**Pull request by Clorr**
Hi @shaoanlu ,

As promised I propose you a split of the class you created so that we have a separated trainer and model and that is compatible with the plugin system

Can you have a look and tell if it suits you and if you are ok to continue this way (Maybe we still can optimize what belongs to the model and what belongs to the trainer)

Note that it is rough and maybe I screwed some things, don't assume I'm a good programmer ;-)

For example, when I run the notebook, it yields:
```
/usr/local/lib/python3.5/dist-packages/keras/engine/training.py:973: UserWarning: Discrepancy between trainable weights and collected trainable weights, did you set `model.trainable` without calling `model.compile` after ?
  'Discrepancy between trainable weights and collected trainable'
```
So maybe I messed something...

### CODE REVIEW

**Comment by shaoanlu** [comment]
Thanks for the efforts, I've checked the script and everything is good. Which one do you think more compatible with deepfakes?

**Comment by Clorr** [comment]
Hi @shaoanlu and thanks for checking,

This version is the best to be integrated in the deepfakes repo. The old plugin in the repo was mostly a draft for preview.

So if it's ok for you, I will take the 2 GANModel and Trainer classes and put them as the official plugins in the deepfakes repo. 

Also I can do the same for the WGAN version. Or do you want to do the split by yourself?

**Comment by shaoanlu** [comment]
Awesome! Thanks for your help! The WGAN is not recommended for plugins because I didn't find any advantage on it compare to previous version. (I called it improved WGAN because its the title of the original paper 😂 )

**Comment by Clorr** [comment]
Great then!

What you can do now is merge the pull request with the button below. It will replace your file in temp/ and so you will be able to continue working on it while keeping compatibility with the plugin system.

And if you have modifications, feel free to let us know so that we take them in the official repo...

Important note: For the future modifications, as long as they are compatible with the model files, they can be made on the same plugin. If you make any incompatible change, can you do it in a new file? That way the users who have trained a model with the plugin are not blocked by the new changes...

**Pull request merged**
